### ISSUE TITLE
Illegal Base64 Data at Input Byte 0 during OKD Bootstrap

### ISSUE THREAD

**Issue by Jess4Tech** [okd-project/okd-scos#12]
**Describe the bug**
When trying to install okd 4.13.0-0.okd-2023-05-22-052007, the bootstrap node repeatedly fails with "illegal base64 data at input byte 0".

It's UPI. I made all the DNS mappings and such.

**How reproducible**
It's happened whenever I try it, but I'm not sure if that's reproducible.

A whole loop of the issue
https://pastebin.com/xJQ1XPdh

My install-config.yaml
```
apiVersion: v1
baseDomain: jessnuko.lan
metadata:
  name: okd

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: 'ssh-ed25519 AAAA....'
```
